// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/foundation.dart';

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDtuxahEVj78OTSIZKaa6z8Q69CNWymO78',
    appId: '1:708576389273:web:15dce7b898db575097f008',
    messagingSenderId: '708576389273',
    projectId: 'servis360-15b4a',
    authDomain: 'servis360-15b4a.firebaseapp.com',
    storageBucket: 'servis360-15b4a.firebasestorage.app',
    measurementId: 'G-FMH5TW36HL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDS9WE7zEoXkkTczO6JC-Dxon4oU9RvYx8',
    appId: '1:708576389273:android:850ea4f6400e954297f008',
    messagingSenderId: '708576389273',
    projectId: 'servis360-15b4a',
    storageBucket: 'servis360-15b4a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAPAX7vJRCltbIXK1AWxekEF5XjUgezWms',
    appId: '1:708576389273:ios:c2129aa0709c172197f008',
    messagingSenderId: '708576389273',
    projectId: 'servis360-15b4a',
    storageBucket: 'servis360-15b4a.firebasestorage.app',
    iosBundleId: 'com.servisim360.app.servisim360',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAPAX7vJRCltbIXK1AWxekEF5XjUgezWms',
    appId: '1:708576389273:ios:c2129aa0709c172197f008',
    messagingSenderId: '708576389273',
    projectId: 'servis360-15b4a',
    storageBucket: 'servis360-15b4a.firebasestorage.app',
    iosBundleId: 'com.servisim360.app.servisim360',
  );
}